### PR TITLE
Updates to codon_tools

### PR DESCRIPTION
**Pull request by weitzner**
This PR contains a complete revamp of the codon_tools script.

* Leverages more Biopython types, data and functions, and enables a simpler method of setting up particular details (e.g. a list of restriction enzymes by name can be passed through at runtime).
* Multiple independent trajectories followed by successive rounds of optimization. The trajectory with the highest CAI that is still within the tolerance of the `relax` parameter is outputted to the user.
* Multiple amino acid sequences input as a single fasta file will also be outputted as a single fasta file.
* All input data is now stored in an importable form (e.g. dictionaries for host codon usage) to simplify loading data.
* Hairpin detection and removal.
* Documentation including type annotations for all functions

Initial testing (running some sample amino acid sequences through the script and then using IDT's codon mapping to estimate complexity) shows this is working, and is typically fast (~90s for 10 sequences of varying length).

### CODE REVIEW

**Comment by weitzner** [comment]
What range of complexities were you seeing initially? What tests can you think of to demonstrate whether or not this is an improvement across the board?

**Comment by yhsia** [comment]
I'm running a couple of test sequences atm.

One sequence keeps returning:
> WARNING:__main__:Unable to create suitable DNA sequence for input sequence 1.

However, if I just add a `W` residue in the beginning, suddenly it works.

I'm also noticing short repetitive sequences like peptides are returning the above issue, and are unable to be fixed by padding; instead of returning the "best plausible result" even though it's not great.

It's kind of odd too, that my original template file `INPUT_LIST.fasta`, it is able to optimize the sequence `HHHHHHHHHH` but it is unable to optimize `ACDEFGHIKLMNPQRSTVWY`

I suspect these issues are related.

**Comment by weitzner** [comment]
Is that happening with the default number of cycles? Does changing the cycles fix it?

**Comment by yhsia** [comment]
Looks like setting `--cycles 100` doesn't help.

Maybe it's an issue with the hairpin optimization?
I say this because 1. I didn't have it before, and 2. adding the W changes the beginning of the sequence.

Perhaps we should add options to turn off specific optimizations?

**Comment by yhsia** [comment]
Ok if I comment out the hairpin optimization, the `W` issue goes away.

Doesn't fix short repetitive peptides though, and still can't optimize `ACDEFGHIKLMNPQRSTVWY`.
It can, however, optimize `ACDEFGHIKLMNPQRSTVWYACDEFGHIKLMNPQRSTVWY` which is just the sequence duplicated.

**Comment by weitzner** [comment]
Interesting. Do you know what the `difference` from the particular codon use profile is that's causing the sequence to be rejected?

**Comment by yhsia** [comment]
for `ACDEFGHIKLMNPQRSTVWY`:

>INFO:codon_tools.util.seq_opt:Current number of deviations from host codon usage profile: 3 over 13 codons
>INFO:codon_tools.util.seq_opt:Current deviation from host codon usage profile: 27%

Did you add code in there that has hard cutoffs?

**Comment by weitzner** [comment]
Yes. If the difference exceeds the relax, it won't be stored.

**Comment by yhsia** [comment]
I tested some irl sequences and dumped them into IDT's calculator. Some of the sequences did not pass their filters. Probably means some of the numbers in the thresholds need to be re-tweaked.

Will dig into it and update you.

**Pull request closed without merging**
